### ISSUE TITLE
Not working over reverse proxies.

### ISSUE THREAD

**Issue by gugahoi** [krixon/xbmc-php-rpc#1]
I've just set up my XBMC to work over a reverse proxy and I notice the parsing of the URL is only intended to work when there is a port argument in the URL. Would it be possible to updated this to also enable simple reverse proxy URLs? 

eg.: http://www.myurl.com/xbmc/     instead of      http://www.myurl.com:8080/

**Comment by Phyks** [comment]
Should be fixed in https://github.com/krixon/xbmc-php-rpc/pull/5.

You could use http://www.myurl.com:80/xbmc/ (port is important, 8080 is still the default one) and it should work.

**Comment by krixon** [comment]
Thanks Phyks.
